name: Create Tag from Commit

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit message
        id: msg
        run: echo "MSG=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Create tag if MSG starts with v
        if: startsWith(steps.msg.outputs.MSG, 'v')
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          version=${{ steps.msg.outputs.MSG }}
          git tag "$version"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} "$version"
